version: "3.8"
services:
  wine-storage:
    build: .
    image: wine-storage
    container_name: wine-storage
    volumes:
      - ./:/www/WineStorage
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:password@postgresql-wine-storage:5432/wine_storage
      - FLASK_ENV=development
      - EDIT_PASSWORD=pass
    ports:
      - 4321:4321
    networks:
      - dev-net
      # uwsgi /www/WineStorage/uwsgi.ini
      # DATABASE_URL=postgres://postgres:password@postgresql-wine-storage:5432/wine_storage uwsgi uwsgi.ini
    entrypoint: ["python", "run_dev.py"]  # start the image and remain running
    # entrypoint: ["tail", "-f", "/dev/null"]  # start the image and remain running
  postgresql:
    image: postgres:14.1
    container_name: postgresql-wine-storage
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=wine_storage
    ports:
      - 3306
    networks:
      - dev-net
networks:
  dev-net:
