"""add_is_archived

Revision ID: 248835a60d6d
Revises: 8ffb808f6ec4
Create Date: 2022-01-07 14:18:49.569155

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "248835a60d6d"
down_revision = "8ffb808f6ec4"
branch_labels = None
depends_on = None


def upgrade():
    """add_is_archived"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "wine",
        sa.Column("is_archived", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    """add_is_archived (rollback)"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wine", "is_archived")
    # ### end Alembic commands ###
